language: php

matrix:
  include:
    - php: 5.5
      env: TYPO3=^7.6.0
    - php: 5.3
      env: TYPO3=^6.2.0

before_install:
  - composer self-update
  - composer --version

before_script:
  - cd ..
  - mkdir typo3.cms
  - cd typo3.cms
  - cp ../phpunit/Tests/Build/composer.json .
  - composer require typo3/cms="$TYPO3"
  - ./typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="localhost" --database-port="3306" --database-name="travis_test" --admin-user-name="admin" --admin-password="password" --site-name="Travis Install"
  - ln -s ../../../../phpunit typo3conf/ext/phpunit
  - ./typo3cms extension:install phpunit
  - mysql -u root travis_test -e "INSERT INTO be_users (username, password) VALUES ('_cli_phpunit', 'password')"

script:
  - php typo3/cli_dispatch.phpsh phpunit -c typo3conf/ext/phpunit/Tests/Build/UnitTests.xml
  - find ../phpunit -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
