language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql TYPO3=master INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-1 INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-0 INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_4-7 INTEGRATION=TYPO3_4-7
  - DB=mysql TYPO3=TYPO3_4-6 INTEGRATION=TYPO3_4-7
  - DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7

matrix:
  include:
    - php: 5.5
      env: DB=mysql TYPO3=master INTEGRATION=master

services:
  - memcached

before_script:
# Install build dependencies
  - cd ..
  - git clone --single-branch --branch $INTEGRATION --depth 1 https://github.com/Konafets/TYPO3-Travis-Integration build-environment
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
  - installPhpModule -y memcache
  - installPhpModule redis
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone --single-branch --branch $TYPO3 --depth 1 git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv core/typo3 .
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
  - mv build-environment/typo3conf .
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - ls -lah .
  - ls -lah typo3conf/
  - ls -lah typo3conf/ext/phpunit/
  - cp -r typo3conf/ext/phpunit/Tests/Unit/Fixtures/Extensions/aaa typo3conf/ext/
  - cp -r typo3conf/ext/phpunit/Tests/Unit/Fixtures/Extensions/bbb typo3conf/ext/
  - cp -r typo3conf/ext/phpunit/Tests/Unit/Fixtures/Extensions/ccc typo3conf/ext/
  - cp -r typo3conf/ext/phpunit/Tests/Unit/Fixtures/Extensions/user_phpunittest typo3conf/ext/
  - cp -r typo3conf/ext/phpunit/Tests/Unit/Fixtures/Extensions/user_phpunittest2 typo3conf/ext/
  - mkdir fileadmin
  - mkdir uploads
  - mkdir typo3temp
  - git clone --single-branch --branch master --depth 1 git://github.com/etobi/ext-coreapi typo3conf/ext/coreapi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ "$DB" == "mysql" && -f  build-environment/dbimport/news.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/news.sql; fi
  - php $PWD/typo3/cli_dispatch.phpsh coreapi database:databasecompare 1,2,3,4,5,6,7,8

script:
#  - phpLint all
  - php $PWD/typo3/cli_dispatch.phpsh phpunit typo3conf/ext/phpunit/Tests/
